### PR TITLE
Makefile tweaks for macOS

### PR DESCRIPTION
**Pull request by jturner**
This adds support for finding the number of logical processors on macOS and other small Makefile cleanups.

### CODE REVIEW

**Comment by Kleidukos** [comment]
Hi @jturner and thank you very much for this contribution! :)

**Comment by Kleidukos** [comment]
I think that you'll have to change this line to accommodate the new version: https://github.com/haskellfoundation/matchmaker/blob/development/shell.nix#L16

**Comment by jturner** [comment]
> I think that you'll have to change this line to accommodate the new version: https://github.com/haskellfoundation/matchmaker/blob/development/shell.nix#L16

Thank you, I've also updated the `.github/workflows/ci.yml` to use 8.10.5 as well.

**Comment by Kleidukos** [comment]
Any chance you could rebase on upstream/development? :)

**Comment by jturner** [comment]
> Any chance you could rebase on upstream/development? :)

Yup, did this with `jturner force-pushed the jturner:macos-cleanup branch from a63f5d1 to 6f2d6e4 15 hours ago`.

It looks like nix doesn't know about ghc8105? `error: attribute 'ghc8105' missing, at /home/runner/work/matchmaker/matchmaker/shell.nix:16:7` I'm no nix expert sadly.

**Comment by jturner** [comment]
So I've looked into this more and it seems the issue is the official nix haskell packages only support `8.10.4`. We would need to either wait until they upgrade to `8.10.5` or use an alternative haskell nixpkg like https://input-output-hk.github.io/haskell.nix, which has support for `8.10.5`.

Sorry for not researching this more. I can close this PR and submit a new one with just the `Makefile` fixes and keep the `8.10.5` changes local for now.

**Comment by Kleidukos** [comment]
Don't bother, you can remove the GHC 8.10.5 changes from this PR. :)

**Comment by jturner** [comment]
> Don't bother, you can remove the GHC 8.10.5 changes from this PR. :)

Done!

**Comment by Kleidukos** [comment]
Since you remove `parallel` in favour of `xargs`, could you  also remove it from `shell.nix`?

**Comment by jturner** [comment]
Rebased and removed the final use of parallel.

**Review by Kleidukos — APPROVED** [review]
Thank you :green_heart: :blue_heart: :purple_heart: :yellow_heart: :heart:

**Pull request merged**
