### PR TITLE
Insert organisation and relationships when creating a new user

### LINKED ISSUE #3: Organisation creation
Each new user is automatically added to its own organisation. We want to have a creation screen for organisations separately.

### PR DESCRIPTION
**Pull request by eviefp**
Closes #3 

TODO:
- [x] validate that `runDB` runs in a transaction
- [x] see what happens if the org name already exists (expectation: error due to conflict, rollback; is this acceptable?)
- [x] add tests

### CODE REVIEW

**Review by elland — DISMISSED** [review]
Looks fine. 😀

**Comment by eviefp** [comment]
I've been very busy this week, but I am looking to pick this up next week, write some tests and get it merged. Sorry about the delay.

**Comment by Kleidukos** [comment]
@eviefp Absolutely no problem!!

**Comment by eviefp** [comment]
Managed to add tests today! Going through the source code, it does seem like `runDB` is using transactions:

- https://github.com/tchoutri/pg-entity/blob/c45277e8a8525737e09de05c5a3b012e5093887a/src/Database/PostgreSQL/Entity/DBT.hs#L44
- https://hackage.haskell.org/package/pg-transact-0.3.2.0/docs/src/Database.PostgreSQL.Transact.html#runDBTSerializable
- https://hackage.haskell.org/package/postgresql-simple-0.6.4/docs/Database-PostgreSQL-Simple-Transaction.html#v:withTransactionSerializable

Also, turns out we can create as many identical (same username, email, displayname) and organisations we want since we don't have UNIQUE constraints and their PK is automatically generated UUIDs. Should I fix any of this with this PR, or should we figure this bit later?

**Review by Kleidukos — CHANGES_REQUESTED** [review]
@eviefp You're right. UNIQUE constraints are needed on `email` and `email`. :)

**Review by Kleidukos — APPROVED** [review]
LGTM

**Pull request merged**
